#!/bin/bash
dir=~/6  #Исследуемая директория
rm $dir/lab1.xls
mkdir ~/vspom
cd ~/vspom

# Название, размер, расширение и дата изменения
ls -lR $dir | sed '/^\//d' | sed '/^d/d' | awk '!/^$/{print $5,$6" "$7" "$8}' OFS=',' | sed '/^,/d' >> size_date.txt 
ls -R --file-type $dir | sed '/^\//d' | sed '/\/$/d' | sed '/^$/d' >> name.txt 
ls -lR $dir | sed '/^\//d' | sed '/^d/d' | sed '/^$/d' | awk -F "." '!/^итого/{if (NF==1) {print "-"} else {print $NF}}' >> type.txt
paste --delimiters=',' name.txt type.txt size_date.txt > lev1.txt
sort lev1.txt > lev.txt

#Тип файла
IFS=$'\n'
files=$( find $dir -type f )
find $dir -type f | awk -F "/" '{print $NF}' > mime_type1.txt
for file in $files; do 
file --mime-type -b "$file" >> mime_type2.txt  
done
paste --delimiters=',' mime_type1.txt mime_type2.txt > mime_type.txt

#Длительность
for file in $files; do 
lek=$(mediainfo "$file" 2>/dev/null | grep --max-count=1 Duration | awk '{print $3,$4}') 
echo -"$lek" >> duration2.txt
done
paste --delimiters=',' mime_type.txt duration2.txt > duration_types1.txt
sort duration_types1.txt | awk -F "," '{print $2,$3}' OFS=',' > duration_types.txt

#В табличку
echo Имя,Расширение,Размер,Дата изменения,Тип,Длительность > $dir/lab1.xls
paste lev.txt duration_types.txt >> $dir/lab1.xls
cd $dir
rm -r ~/vspom
