#!/bin/bash
dir=~/6  #Исследуемая директория
rm $dir/lab1.xls
mkdir ~/vspom
cd ~/vspom

# Название, размер, расширение и дата изменения
echo Название,Размер,Дата изменения > lab1.1.txt
ls -l $dir | awk '{print $9 $10 $11,$5,$6" "$7" "$8}' OFS=',' >> lab1.1.txt 
echo Расширение > lab1.4.txt
ls -l $dir | awk -F "." '{if (NF==1) {print "-"} else {print $NF}}' >> lab1.4.txt

#Длительность
echo Длительность > lab1.3.txt
echo \ >> lab1.3.txt
for file in $dir/*; do 
lek=$(mediainfo $file | grep --max-count=1 Duration | awk '{print $3,$4}') 
echo -$lek >> lab1.3.txt
done

#В табличку
paste lab1.1.txt lab1.3.txt lab1.4.txt >> $dir/lab1.xls
cd $dir
rm -r ~/vspom
